#!/bin/bash

./ecj-pagie1-addInd-noFv-30.sh
./ecj-pagie2-addInd-noFv-30.sh
./ecj-keijzer1-addInd-noFv-30.sh
./ecj-keijzer2-addInd-noFv-30.sh
./ecj-keijzer3-addInd-noFv-30.sh
./ecj-keijzer4-addInd-noFv-30.sh
./ecj-keijzer5-addInd-noFv-30.sh
./ecj-keijzer6-addInd-noFv-30.sh
./ecj-keijzer7-addInd-noFv-30.sh
./ecj-keijzer8-addInd-noFv-30.sh
./ecj-keijzer9-addInd-noFv-30.sh
./ecj-keijzer10-addInd-noFv-30.sh
./ecj-keijzer11-addInd-noFv-30.sh
./ecj-keijzer12-addInd-noFv-30.sh
./ecj-keijzer13-addInd-noFv-30.sh
./ecj-keijzer14-addInd-noFv-30.sh
./ecj-keijzer15-addInd-noFv-30.sh
./ecj-vladislavleva1-addInd-noFv-30.sh
./ecj-vladislavleva2-addInd-noFv-30.sh
./ecj-vladislavleva3-addInd-noFv-30.sh
./ecj-vladislavleva4-addInd-noFv-30.sh
./ecj-vladislavleva5-addInd-noFv-30.sh
./ecj-vladislavleva6-addInd-noFv-30.sh
./ecj-vladislavleva7-addInd-noFv-30.sh
./ecj-vladislavleva8-addInd-noFv-30.sh
